/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sw;
import java.io.IOException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.plaf.metal.MetalBorders;
import javax.swing.table.DefaultTableModel;
import static sw.Main.*;
/**
 *
 * @author NSH
 */
public class Admin extends javax.swing.JFrame {
    
    static Connection conn;
    static Statement stmt;
    static PreparedStatement pstmt;
    static ResultSet rs;
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }
    private void DB_open(){
        try{
            conn = DriverManager.getConnection(orcle_url, orcle_ID, orcle_PW);
            stmt = conn.createStatement();
            System.out.println("Con DB");
        }catch(Exception e){
            System.out.println("dbOpenErr");
            System.out.println("SQLException : " + e.getMessage());
        }
    }
    
    private int getDBdata(String SQL){
        String User_ID = null; 
        String User_Name = null;
        String User_RemainTime = null;
        int cnt = 0;
        DefaultTableModel model = (DefaultTableModel)tabTimeDB.getModel();
        model.setRowCount(0);
        try{
            DB_open();
            rs = stmt.executeQuery(SQL);
            while(rs.next()){
                User_Name = rs.getString("user_name");
                User_ID = rs.getString("user_id");
                User_RemainTime = rs.getString("user_remainTime");
                model.addRow(new Object[]{User_ID,User_Name,User_RemainTime});
                cnt = rs.getRow();
            }
        }catch(Exception e){
            System.out.println("getDBdataerr");
            System.out.println("SQLException : "+e.getMessage());
        }
        tabTimeDB.setModel(model);
        return cnt;
    }
    
    private void setDBdata(String name, String id, int time){
        int cnt = 0;
        String SQL = "";
        if (!name.isEmpty() && id.isEmpty()) {
            System.out.println("name");
            SQL = "update users set user_remainTime = ? where user_name = ?";
            cnt = 1;
        } else if (name.isEmpty() && !id.isEmpty()) {
            System.out.println("id");
            SQL = "update users set user_remainTime = ? where user_id = ?";
            cnt = 2;
        } else if (!name.isEmpty() && !id.isEmpty()) {
            System.out.println("two");
            SQL = "update users set user_remainTime = ? where user_id = ? and user_name = ?";
            cnt = 3;
        }
        System.out.println("setDBOK");
        try{
            DB_open();
            pstmt = conn.prepareStatement(SQL);
            pstmt.setInt(1, time);
            if(cnt == 1)
                pstmt.setString(2, name);
            if(cnt == 2)
                pstmt.setString(2,id);
            if(cnt == 3){
                pstmt.setString(2, id);
                pstmt.setString(3,name);
            }
            pstmt.executeUpdate();    
//            if(cnt == 1) getDBdata("Select * from users where user_name = '"+name+"'");
//            if(cnt == 2) getDBdata("Select * from users where user_id = '"+id+"'");
//            if(cnt == 3) getDBdata("Select * from users where user_id = '"+id+"' and user_name = '"+name+"'");
            getDBdata("Select * from users");
            System.out.println(SQL);
        }catch(Exception e){
            System.out.println("setDBerr");
            System.out.println("SQLException : "+e.getMessage());
        }
    }
    
    private void SelectedTab(){
        int row = tabTimeDB.getSelectedRow();
        Object value = tabTimeDB.getValueAt(row,0);
        txtNameMenu.setText((String) value);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        Main = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnInventory1 = new javax.swing.JButton();
        btnTime1 = new javax.swing.JButton();
        Inventory = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabMenuDB = new javax.swing.JTable();
        btnAllSearchMenu = new javax.swing.JButton();
        txtNameMenu = new javax.swing.JTextField();
        lblName1 = new javax.swing.JLabel();
        btnSearchFood = new javax.swing.JButton();
        btnSoldOut = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        lblTimeMan1 = new javax.swing.JLabel();
        btnPriceChange = new javax.swing.JButton();
        txtPriceChange = new javax.swing.JTextField();
        lblName2 = new javax.swing.JLabel();
        Time = new javax.swing.JPanel();
        btnAllSearch = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtTime1 = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        btnTime = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabTimeDB = new javax.swing.JTable();
        lblID = new javax.swing.JLabel();
        lblBack1 = new javax.swing.JLabel();
        lblTimeMan2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(35, 35, 35));
        getContentPane().setLayout(new java.awt.CardLayout());

        Main.setBackground(new java.awt.Color(35, 35, 35));

        jButton1.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jButton1.setText("종료");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnInventory1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        btnInventory1.setText("상품 관리");
        btnInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventory1ActionPerformed(evt);
            }
        });

        btnTime1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        btnTime1.setText("시간 관리");
        btnTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTime1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(btnTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInventory1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        getContentPane().add(Main, "card4");

        Inventory.setBackground(new java.awt.Color(35, 35, 35));

        tabMenuDB.setBackground(new java.awt.Color(204, 204, 204));
        tabMenuDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "메뉴이름", "가격", "재고"
            }
        ));
        tabMenuDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMenuDBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabMenuDB);

        btnAllSearchMenu.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnAllSearchMenu.setText("전체검색");
        btnAllSearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllSearchMenuActionPerformed(evt);
            }
        });

        txtNameMenu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameMenuActionPerformed(evt);
            }
        });

        lblName1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblName1.setForeground(new java.awt.Color(255, 255, 255));
        lblName1.setText("음식이름");

        btnSearchFood.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnSearchFood.setText("검색");
        btnSearchFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchFoodActionPerformed(evt);
            }
        });

        btnSoldOut.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnSoldOut.setText("품절");
        btnSoldOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoldOutActionPerformed(evt);
            }
        });

        lblBack.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setText("◀");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        lblTimeMan1.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lblTimeMan1.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeMan1.setText("상품 관리");

        btnPriceChange.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnPriceChange.setText("가격 수정");
        btnPriceChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceChangeActionPerformed(evt);
            }
        });

        txtPriceChange.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPriceChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceChangeActionPerformed(evt);
            }
        });

        lblName2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblName2.setForeground(new java.awt.Color(255, 255, 255));
        lblName2.setText("가격수정");

        javax.swing.GroupLayout InventoryLayout = new javax.swing.GroupLayout(Inventory);
        Inventory.setLayout(InventoryLayout);
        InventoryLayout.setHorizontalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBack)
                .addGap(290, 290, 290)
                .addComponent(lblTimeMan1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InventoryLayout.createSequentialGroup()
                                .addComponent(btnAllSearchMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnSoldOut, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(btnPriceChange, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InventoryLayout.createSequentialGroup()
                                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPriceChange, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(InventoryLayout.createSequentialGroup()
                                        .addComponent(txtNameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearchFood, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        InventoryLayout.setVerticalGroup(
            InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InventoryLayout.createSequentialGroup()
                .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InventoryLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InventoryLayout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(lblTimeMan1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchFood, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPriceChange, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(InventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAllSearchMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSoldOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPriceChange, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(Inventory, "card5");

        Time.setBackground(new java.awt.Color(35, 35, 35));

        btnAllSearch.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        btnAllSearch.setText("전체 회원 검색");
        btnAllSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("검색");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("이름");

        txtTime1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTime1ActionPerformed(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("변경 시간");

        btnTime.setText("시간 설정");
        btnTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeActionPerformed(evt);
            }
        });

        tabTimeDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "이름", "남은시간"
            }
        ));
        tabTimeDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabTimeDBMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabTimeDB);

        lblID.setFont(new java.awt.Font("맑은 고딕", 1, 16)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");

        lblBack1.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblBack1.setForeground(new java.awt.Color(255, 255, 255));
        lblBack1.setText("◀");
        lblBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBack1MouseClicked(evt);
            }
        });

        lblTimeMan2.setFont(new java.awt.Font("맑은 고딕", 1, 20)); // NOI18N
        lblTimeMan2.setForeground(new java.awt.Color(255, 255, 255));
        lblTimeMan2.setText("시간 관리");

        javax.swing.GroupLayout TimeLayout = new javax.swing.GroupLayout(Time);
        Time.setLayout(TimeLayout);
        TimeLayout.setHorizontalGroup(
            TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeLayout.createSequentialGroup()
                .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TimeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeLayout.createSequentialGroup()
                                .addComponent(lblBack1)
                                .addGap(304, 304, 304))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeLayout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAllSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)))
                        .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimeMan2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TimeLayout.createSequentialGroup()
                                .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(TimeLayout.createSequentialGroup()
                                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(TimeLayout.createSequentialGroup()
                                        .addComponent(lblTime)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTime1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(TimeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
        );
        TimeLayout.setVerticalGroup(
            TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TimeLayout.createSequentialGroup()
                .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack1))
                    .addGroup(TimeLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblTimeMan2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(TimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAllSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        getContentPane().add(Time, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllSearchActionPerformed
        getDBdata("Select * from users");
    }//GEN-LAST:event_btnAllSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String name = txtName.getText();
        String id = txtID.getText();
        ckDBdata(name, id);
        
    }//GEN-LAST:event_btnSearchActionPerformed
    private int ckDBdata(String name, String id){
        int ck = 0;
        if(name.equals("") && id.equals("")){
            JOptionPane.showMessageDialog(null, "id혹은 이름을 입력해주세요.");
        }else if(name.equals("") || id.equals("")){
            if(!name.equals("")){
                ck = getDBdata("Select * from users where User_Name = '"+name+"'");
                return ck;
            }else if(!id.equals("")){
                ck = getDBdata("select * from users where User_ID = '"+id+"'");
                return ck;
            }
        }else{
            ck = getDBdata("select * from users where User_Name= '"+name+"' and user_id = '"+id+"'");
            return ck;
        }
        return -1;
    }
    private void btnTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeActionPerformed
        try{
            int time = Integer.parseInt(txtTime1.getText());
            String name = txtName.getText();
            String id = txtID.getText();
            System.out.println(time);
            int cnt = 0;
            if(0==ckDBdata(name, id)){
                JOptionPane.showMessageDialog(null, "조회되지 않는 유저입니다 올바르게 입력해주세요.");
            }else{
                if(time <= -1){
                    JOptionPane.showMessageDialog(null, "시간을 제대로 넣어주세요");
                }else{
                    setDBdata(name, id, time);
                }
//                cnt = ckDBdata(name,id);
//                if(time == 0){
//                    JOptionPane.showMessageDialog(null, "시간을 제대로 넣어주세요");
//                }else if(cnt>=2){
//                    int option = JOptionPane.showConfirmDialog(this, "동일한 이름을 가진 유저가 "+cnt+"명 있습니다.\n전부 시간을 수정하시겠습니까?","알림창",JOptionPane.YES_NO_CANCEL_OPTION);
//                    if(option==JOptionPane.YES_OPTION)
//                        setDBdata(name, id, time);
//                }else{
//                    setDBdata(name, id, time);
//                }
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"올바른 숫자를 입력하세요");
        }        
    }//GEN-LAST:event_btnTimeActionPerformed
    private int getDBdataFood(String SQL){
        String Menu_Name = null; 
        String Menu_STOCK = null;
        String Menu_Price = null;
        int cnt = 0;
        DefaultTableModel model1 = (DefaultTableModel)tabMenuDB.getModel();
        model1.setRowCount(0);
        try{
            DB_open();
            rs = stmt.executeQuery(SQL);
            while(rs.next()){
                Menu_Name = rs.getString("Menu_Name");
                Menu_STOCK = rs.getString("Menu_STOCK");
                Menu_Price = rs.getString("Menu_Price");
                model1.addRow(new Object[]{Menu_Name, Menu_Price, Menu_STOCK});
                cnt = rs.getRow();
            }
        }catch(Exception e){
            System.out.println("SQLException : "+e.getMessage());
        }
        tabMenuDB.setModel(model1);
        return cnt;
    }
    
    private void setDBdataFood(String FoodName, String stock){
        String SQL = "update menu set menu_stock = ? where menu_name = ?";
        int row = tabMenuDB.getSelectedRow();
        try{
            DB_open();
            System.out.println(row);
            pstmt = conn.prepareStatement(SQL);
            if(stock.equals("no") || stock.equals("No")){
                pstmt.setString(1, "yes");
            }else{
                pstmt.setString(1, "no");
            }
            
            pstmt.setString(2,FoodName);
            pstmt.executeUpdate();    
            getDBdataFood("Select * from menu");
        }catch(Exception e){
            System.out.println("setDBerr");
            System.out.println("SQLException : "+e.getMessage());
        }
    }
    
    private void setDBdataPrice(String FoodName, String Price){
        String SQL = "update menu set menu_price = ? where menu_name = ?";
        try{
            DB_open();
            pstmt = conn.prepareStatement(SQL);
            pstmt.setString(1, Price);
            pstmt.setString(2,FoodName);
            pstmt.executeUpdate();    
            getDBdataFood("Select * from menu");
        }catch(Exception e){
            System.out.println("setDBerr");
            System.out.println("SQLException : "+e.getMessage());
        }
    }
    private void btnAllSearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllSearchMenuActionPerformed
        getDBdataFood("Select * from menu");
    }//GEN-LAST:event_btnAllSearchMenuActionPerformed

    private void btnSearchFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFoodActionPerformed
        String FoodName = "%"+txtNameMenu.getText()+"%";
        if(FoodName.equals("")){
            JOptionPane.showMessageDialog(null,"음식명을 올바르게 입력해주세요");
        }else{
            if(getDBdataFood("Select * from menu where Menu_name like '"+FoodName+"'")==0)
                JOptionPane.showMessageDialog(null,"검색한 음식은 없습니다.");
        }
    }//GEN-LAST:event_btnSearchFoodActionPerformed

    private void btnSoldOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoldOutActionPerformed
        String FoodName = txtNameMenu.getText();
        if(FoodName.equals("")){
            JOptionPane.showMessageDialog(null,"음식명을 올바르게 입력해주세요");
        }else{
            int row = tabMenuDB.getSelectedRow();
            Object stock = tabMenuDB.getValueAt(row, 2);
            System.out.println((String)tabMenuDB.getValueAt(row,0));
            if(!FoodName.equals((String)tabMenuDB.getValueAt(row,0))){
                JOptionPane.showMessageDialog(null,"검색한 음식은 없습니다.");
            }else{
                setDBdataFood(FoodName, (String)stock);
            }
        }
    }//GEN-LAST:event_btnSoldOutActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        Main.setVisible(true);
        Inventory.setVisible(false);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseClicked
        Main.setVisible(true);
        Time.setVisible(false);
    }//GEN-LAST:event_lblBack1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventory1ActionPerformed
        Inventory.setVisible(true);
        Main.setVisible(false);
    }//GEN-LAST:event_btnInventory1ActionPerformed

    private void btnTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTime1ActionPerformed
        Time.setVisible(true);
        Main.setVisible(false);
    }//GEN-LAST:event_btnTime1ActionPerformed

    private void btnPriceChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceChangeActionPerformed
        String price = txtPriceChange.getText();
        String FoodName = txtNameMenu.getText();
        setDBdataPrice(FoodName, price);
    }//GEN-LAST:event_btnPriceChangeActionPerformed

    private void tabMenuDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMenuDBMouseClicked
        int row = tabMenuDB.getSelectedRow();
        System.out.println(row);
        Object value = tabMenuDB.getValueAt(row,0);
        txtNameMenu.setText((String) value);
        value = tabMenuDB.getValueAt(row,1);
        txtPriceChange.setText((String) value);
        
    }//GEN-LAST:event_tabMenuDBMouseClicked

    private void tabTimeDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabTimeDBMouseClicked
        int row = tabTimeDB.getSelectedRow();
        System.out.println(row);
        Object value = tabTimeDB.getValueAt(row,0);
        txtID.setText((String) value);
        value = tabTimeDB.getValueAt(row,1);
        txtName.setText((String) value);
        value = tabTimeDB.getValueAt(row, 2);
        txtTime1.setText((String) value);
    }//GEN-LAST:event_tabTimeDBMouseClicked

    private void txtNameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameMenuActionPerformed
        btnSearchFoodActionPerformed(evt);
    }//GEN-LAST:event_txtNameMenuActionPerformed

    private void txtPriceChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceChangeActionPerformed
        btnPriceChangeActionPerformed(evt);
    }//GEN-LAST:event_txtPriceChangeActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        btnSearchActionPerformed(evt);
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        btnSearchActionPerformed(evt);
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTime1ActionPerformed
        btnTimeActionPerformed(evt);
    }//GEN-LAST:event_txtTime1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inventory;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Time;
    private javax.swing.JButton btnAllSearch;
    private javax.swing.JButton btnAllSearchMenu;
    private javax.swing.JButton btnInventory1;
    private javax.swing.JButton btnPriceChange;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearchFood;
    private javax.swing.JButton btnSoldOut;
    private javax.swing.JButton btnTime;
    private javax.swing.JButton btnTime1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBack1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeMan1;
    private javax.swing.JLabel lblTimeMan2;
    private javax.swing.JTable tabMenuDB;
    private javax.swing.JTable tabTimeDB;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameMenu;
    private javax.swing.JTextField txtPriceChange;
    private javax.swing.JTextField txtTime1;
    // End of variables declaration//GEN-END:variables
}
