package sw;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import static sw.Main.orcle_ID;
import static sw.Main.orcle_PW;
import static sw.Main.orcle_url;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author IMBLOP
 */
public class FindUser extends javax.swing.JFrame {

    String phoneNum;
    String userName;
    String userBirth;
    String userID;


    public FindUser() {
        initComponents();
        lblWarn.setForeground(Choose.getBackground());
        lblWarn1.setForeground(Choose.getBackground());
        lblCheck.setVisible(false);
        txtCheck.setVisible(false);
        btnCheck.setVisible(false);
        lblCheck1.setVisible(false);
        txtCheck1.setVisible(false);
        btnCheck1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Choose = new javax.swing.JPanel();
        btnFindPW = new javax.swing.JButton();
        btnFindID = new javax.swing.JButton();
        FindID = new javax.swing.JPanel();
        Check = new javax.swing.JPanel();
        radioKT = new javax.swing.JRadioButton();
        radioSKT = new javax.swing.JRadioButton();
        radioLG = new javax.swing.JRadioButton();
        lblTitle = new javax.swing.JLabel();
        lblCom = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtBirth = new javax.swing.JTextField();
        lblN = new javax.swing.JLabel();
        lblBirth = new javax.swing.JLabel();
        txtPN1 = new javax.swing.JTextField();
        lblPN = new javax.swing.JLabel();
        txtPN2 = new javax.swing.JTextField();
        txtPN3 = new javax.swing.JTextField();
        lblHypen1 = new javax.swing.JLabel();
        lblHypen2 = new javax.swing.JLabel();
        btnCheckRequest = new javax.swing.JButton();
        txtCheck = new javax.swing.JTextField();
        lblCheck = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        lblBack2 = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        InputID = new javax.swing.JPanel();
        lblInputID = new javax.swing.JLabel();
        lblFindPW = new javax.swing.JLabel();
        txtInputID = new javax.swing.JTextField();
        btnInputID = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        FindPW = new javax.swing.JPanel();
        Check1 = new javax.swing.JPanel();
        radioKT1 = new javax.swing.JRadioButton();
        radioSKT1 = new javax.swing.JRadioButton();
        radioLG1 = new javax.swing.JRadioButton();
        lblTitle1 = new javax.swing.JLabel();
        lblCom2 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        txtBirth1 = new javax.swing.JTextField();
        lblN1 = new javax.swing.JLabel();
        lblBirth1 = new javax.swing.JLabel();
        txtPN4 = new javax.swing.JTextField();
        lblPN1 = new javax.swing.JLabel();
        txtPN5 = new javax.swing.JTextField();
        txtPN6 = new javax.swing.JTextField();
        lblHypen3 = new javax.swing.JLabel();
        lblHypen4 = new javax.swing.JLabel();
        btnCheckRequest1 = new javax.swing.JButton();
        txtCheck1 = new javax.swing.JTextField();
        lblCheck1 = new javax.swing.JLabel();
        btnCheck1 = new javax.swing.JButton();
        lblBack3 = new javax.swing.JLabel();
        lblCom5 = new javax.swing.JLabel();
        ChangePW = new javax.swing.JPanel();
        lblChangePW = new javax.swing.JLabel();
        btnChangePW = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblPW = new javax.swing.JLabel();
        lblPWC = new javax.swing.JLabel();
        lblWarn = new javax.swing.JLabel();
        lblWarn1 = new javax.swing.JLabel();
        Input_PW_text = new javax.swing.JPasswordField();
        Input_PWC_text = new javax.swing.JPasswordField();
        lblBack4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Choose.setBackground(new java.awt.Color(35, 35, 35));

        btnFindPW.setText("비밀번호 찾기");
        btnFindPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindPWActionPerformed(evt);
            }
        });

        btnFindID.setText("아이디 찾기");
        btnFindID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChooseLayout = new javax.swing.GroupLayout(Choose);
        Choose.setLayout(ChooseLayout);
        ChooseLayout.setHorizontalGroup(
            ChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnFindID, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnFindPW, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        ChooseLayout.setVerticalGroup(
            ChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChooseLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(ChooseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindPW, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        getContentPane().add(Choose, "card2");

        FindID.setBackground(new java.awt.Color(35, 35, 35));

        Check.setBackground(new java.awt.Color(35, 35, 35));
        Check.setMaximumSize(new java.awt.Dimension(405, 410));
        Check.setMinimumSize(new java.awt.Dimension(405, 410));

        radioKT.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        radioKT.setForeground(new java.awt.Color(255, 255, 255));
        radioKT.setSelected(true);
        radioKT.setText("KT");

        radioSKT.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        radioSKT.setForeground(new java.awt.Color(255, 255, 255));
        radioSKT.setText("SKT");

        radioLG.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        radioLG.setForeground(new java.awt.Color(255, 255, 255));
        radioLG.setText("LG U+");

        lblTitle.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("아이디 찾기");

        lblCom.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblCom.setForeground(new java.awt.Color(255, 255, 255));
        lblCom.setText("통신사");

        txtName.setBackground(new java.awt.Color(25, 25, 25));
        txtName.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtName.setToolTipText("");
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtBirth.setBackground(new java.awt.Color(25, 25, 25));
        txtBirth.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtBirth.setForeground(new java.awt.Color(255, 255, 255));
        txtBirth.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtBirth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblN.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblN.setForeground(new java.awt.Color(255, 255, 255));
        lblN.setText("이름");

        lblBirth.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblBirth.setForeground(new java.awt.Color(255, 255, 255));
        lblBirth.setText("생년월일 8자리");

        txtPN1.setBackground(new java.awt.Color(25, 25, 25));
        txtPN1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtPN1.setForeground(new java.awt.Color(255, 255, 255));
        txtPN1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPN1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblPN.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPN.setForeground(new java.awt.Color(255, 255, 255));
        lblPN.setText("전화번호");

        txtPN2.setBackground(new java.awt.Color(25, 25, 25));
        txtPN2.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtPN2.setForeground(new java.awt.Color(255, 255, 255));
        txtPN2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPN2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtPN3.setBackground(new java.awt.Color(25, 25, 25));
        txtPN3.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtPN3.setForeground(new java.awt.Color(255, 255, 255));
        txtPN3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPN3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblHypen1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblHypen1.setForeground(new java.awt.Color(255, 255, 255));
        lblHypen1.setText("-");

        lblHypen2.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblHypen2.setForeground(new java.awt.Color(255, 255, 255));
        lblHypen2.setText("-");

        btnCheckRequest.setBackground(new java.awt.Color(211, 211, 211));
        btnCheckRequest.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnCheckRequest.setText("인증 요청");
        btnCheckRequest.setPreferredSize(new java.awt.Dimension(269, 26));
        btnCheckRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckRequestActionPerformed(evt);
            }
        });

        txtCheck.setBackground(new java.awt.Color(25, 25, 25));
        txtCheck.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtCheck.setForeground(new java.awt.Color(255, 255, 255));
        txtCheck.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblCheck.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblCheck.setForeground(new java.awt.Color(255, 255, 255));
        lblCheck.setText("인증번호");

        btnCheck.setBackground(new java.awt.Color(211, 211, 211));
        btnCheck.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnCheck.setText("인증 완료");
        btnCheck.setPreferredSize(new java.awt.Dimension(269, 26));
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblBack2.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblBack2.setForeground(new java.awt.Color(255, 255, 255));
        lblBack2.setText("◀");
        lblBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBack2MouseClicked(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("맑은 고딕", 0, 10)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblInfo.setText("회원정보에 등록한 휴대전화 번호와 일치해야 합니다.");

        javax.swing.GroupLayout CheckLayout = new javax.swing.GroupLayout(Check);
        Check.setLayout(CheckLayout);
        CheckLayout.setHorizontalGroup(
            CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckLayout.createSequentialGroup()
                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CheckLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CheckLayout.createSequentialGroup()
                                        .addComponent(lblBack2)
                                        .addGap(90, 90, 90)
                                        .addComponent(lblTitle))
                                    .addGroup(CheckLayout.createSequentialGroup()
                                        .addComponent(lblCom)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioKT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioSKT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioLG, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CheckLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CheckLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CheckLayout.createSequentialGroup()
                                .addComponent(lblCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCheckRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(CheckLayout.createSequentialGroup()
                                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBirth)
                                    .addComponent(lblN, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPN, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CheckLayout.createSequentialGroup()
                                        .addComponent(txtPN1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblHypen1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPN2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(lblHypen2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(txtPN3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
        );
        CheckLayout.setVerticalGroup(
            CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckLayout.createSequentialGroup()
                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CheckLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTitle))
                    .addGroup(CheckLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfo)
                .addGap(10, 10, 10)
                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioLG)
                    .addComponent(radioSKT)
                    .addComponent(radioKT)
                    .addComponent(lblCom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPN)
                    .addComponent(txtPN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHypen1)
                    .addComponent(lblHypen2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CheckLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCheck, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FindIDLayout = new javax.swing.GroupLayout(FindID);
        FindID.setLayout(FindIDLayout);
        FindIDLayout.setHorizontalGroup(
            FindIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(FindIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FindIDLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );
        FindIDLayout.setVerticalGroup(
            FindIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(FindIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FindIDLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(FindID, "card3");

        InputID.setBackground(new java.awt.Color(35, 35, 35));

        lblInputID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblInputID.setForeground(new java.awt.Color(255, 255, 255));
        lblInputID.setText("비밀번호를 찾고자하는 아이디를 입력해주세요.");

        lblFindPW.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblFindPW.setForeground(new java.awt.Color(255, 255, 255));
        lblFindPW.setText("비밀번호 찾기");

        txtInputID.setBackground(new java.awt.Color(25, 25, 25));
        txtInputID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtInputID.setForeground(new java.awt.Color(255, 255, 255));
        txtInputID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtInputID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnInputID.setBackground(new java.awt.Color(211, 211, 211));
        btnInputID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnInputID.setText("다음");
        btnInputID.setPreferredSize(new java.awt.Dimension(269, 26));
        btnInputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputIDActionPerformed(evt);
            }
        });

        lblBack.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setText("◀");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InputIDLayout = new javax.swing.GroupLayout(InputID);
        InputID.setLayout(InputIDLayout);
        InputIDLayout.setHorizontalGroup(
            InputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputIDLayout.createSequentialGroup()
                .addGroup(InputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputIDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack)
                        .addGap(90, 90, 90)
                        .addComponent(lblFindPW))
                    .addGroup(InputIDLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(InputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblInputID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInputID)
                            .addComponent(btnInputID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        InputIDLayout.setVerticalGroup(
            InputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputIDLayout.createSequentialGroup()
                .addGroup(InputIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputIDLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblFindPW))
                    .addGroup(InputIDLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack)))
                .addGap(81, 81, 81)
                .addComponent(lblInputID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInputID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        getContentPane().add(InputID, "card5");

        FindPW.setBackground(new java.awt.Color(35, 35, 35));

        Check1.setBackground(new java.awt.Color(35, 35, 35));
        Check1.setMaximumSize(new java.awt.Dimension(405, 410));
        Check1.setMinimumSize(new java.awt.Dimension(405, 410));

        radioKT1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        radioKT1.setForeground(new java.awt.Color(255, 255, 255));
        radioKT1.setSelected(true);
        radioKT1.setText("KT");

        radioSKT1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        radioSKT1.setForeground(new java.awt.Color(255, 255, 255));
        radioSKT1.setText("SKT");

        radioLG1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        radioLG1.setForeground(new java.awt.Color(255, 255, 255));
        radioLG1.setText("LG U+");

        lblTitle1.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("비밀번호 찾기");

        lblCom2.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblCom2.setForeground(new java.awt.Color(255, 255, 255));
        lblCom2.setText("통신사");

        txtName1.setBackground(new java.awt.Color(25, 25, 25));
        txtName1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtName1.setForeground(new java.awt.Color(255, 255, 255));
        txtName1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtName1.setToolTipText("");
        txtName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtBirth1.setBackground(new java.awt.Color(25, 25, 25));
        txtBirth1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtBirth1.setForeground(new java.awt.Color(255, 255, 255));
        txtBirth1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtBirth1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblN1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblN1.setForeground(new java.awt.Color(255, 255, 255));
        lblN1.setText("이름");

        lblBirth1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblBirth1.setForeground(new java.awt.Color(255, 255, 255));
        lblBirth1.setText("생년월일 8자리");

        txtPN4.setBackground(new java.awt.Color(25, 25, 25));
        txtPN4.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtPN4.setForeground(new java.awt.Color(255, 255, 255));
        txtPN4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPN4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblPN1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPN1.setForeground(new java.awt.Color(255, 255, 255));
        lblPN1.setText("전화번호");

        txtPN5.setBackground(new java.awt.Color(25, 25, 25));
        txtPN5.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtPN5.setForeground(new java.awt.Color(255, 255, 255));
        txtPN5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPN5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtPN6.setBackground(new java.awt.Color(25, 25, 25));
        txtPN6.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtPN6.setForeground(new java.awt.Color(255, 255, 255));
        txtPN6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPN6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblHypen3.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblHypen3.setForeground(new java.awt.Color(255, 255, 255));
        lblHypen3.setText("-");

        lblHypen4.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblHypen4.setForeground(new java.awt.Color(255, 255, 255));
        lblHypen4.setText("-");

        btnCheckRequest1.setBackground(new java.awt.Color(211, 211, 211));
        btnCheckRequest1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnCheckRequest1.setText("인증 요청");
        btnCheckRequest1.setPreferredSize(new java.awt.Dimension(269, 26));
        btnCheckRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckRequest1ActionPerformed(evt);
            }
        });

        txtCheck1.setBackground(new java.awt.Color(25, 25, 25));
        txtCheck1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        txtCheck1.setForeground(new java.awt.Color(255, 255, 255));
        txtCheck1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCheck1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblCheck1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblCheck1.setForeground(new java.awt.Color(255, 255, 255));
        lblCheck1.setText("인증번호");

        btnCheck1.setBackground(new java.awt.Color(211, 211, 211));
        btnCheck1.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnCheck1.setText("인증 완료");
        btnCheck1.setPreferredSize(new java.awt.Dimension(269, 26));
        btnCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheck1ActionPerformed(evt);
            }
        });

        lblBack3.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblBack3.setForeground(new java.awt.Color(255, 255, 255));
        lblBack3.setText("◀");
        lblBack3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBack3MouseClicked(evt);
            }
        });

        lblCom5.setFont(new java.awt.Font("맑은 고딕", 0, 10)); // NOI18N
        lblCom5.setForeground(new java.awt.Color(255, 255, 255));
        lblCom5.setText("회원정보에 등록한 휴대전화 번호와 일치해야 합니다.");

        javax.swing.GroupLayout Check1Layout = new javax.swing.GroupLayout(Check1);
        Check1.setLayout(Check1Layout);
        Check1Layout.setHorizontalGroup(
            Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Check1Layout.createSequentialGroup()
                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Check1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Check1Layout.createSequentialGroup()
                                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Check1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblCom2))
                                    .addGroup(Check1Layout.createSequentialGroup()
                                        .addComponent(lblBack3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Check1Layout.createSequentialGroup()
                                        .addComponent(radioKT1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioSKT1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioLG1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTitle1)))
                            .addGroup(Check1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblCom5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Check1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(Check1Layout.createSequentialGroup()
                                .addComponent(lblCheck1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCheckRequest1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Check1Layout.createSequentialGroup()
                                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBirth1)
                                    .addComponent(lblN1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPN1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBirth1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Check1Layout.createSequentialGroup()
                                        .addComponent(txtPN4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblHypen3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPN5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(lblHypen4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(txtPN6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnCheck1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(62, 62, 62))
        );
        Check1Layout.setVerticalGroup(
            Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Check1Layout.createSequentialGroup()
                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Check1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack3))
                    .addGroup(Check1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblTitle1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCom5)
                .addGap(15, 15, 15)
                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioLG1)
                    .addComponent(radioSKT1)
                    .addComponent(radioKT1)
                    .addComponent(lblCom2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBirth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBirth1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPN1)
                    .addComponent(txtPN4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPN5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPN6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHypen3)
                    .addComponent(lblHypen4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckRequest1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Check1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCheck1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCheck1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FindPWLayout = new javax.swing.GroupLayout(FindPW);
        FindPW.setLayout(FindPWLayout);
        FindPWLayout.setHorizontalGroup(
            FindPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(FindPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FindPWLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Check1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        FindPWLayout.setVerticalGroup(
            FindPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
            .addGroup(FindPWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FindPWLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(Check1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(FindPW, "card4");

        ChangePW.setBackground(new java.awt.Color(35, 35, 35));
        ChangePW.setMaximumSize(new java.awt.Dimension(405, 410));
        ChangePW.setMinimumSize(new java.awt.Dimension(405, 410));

        lblChangePW.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lblChangePW.setForeground(new java.awt.Color(255, 255, 255));
        lblChangePW.setText("비밀번호 변경");

        btnChangePW.setBackground(new java.awt.Color(211, 211, 211));
        btnChangePW.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnChangePW.setText("비밀번호 변경");
        btnChangePW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePWActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(211, 211, 211));
        btnCancel.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnCancel.setText("취소");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblPW.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPW.setForeground(new java.awt.Color(255, 255, 255));
        lblPW.setText("비밀번호");

        lblPWC.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPWC.setForeground(new java.awt.Color(255, 255, 255));
        lblPWC.setText("비밀번호 확인");

        lblWarn.setForeground(new java.awt.Color(255, 0, 0));
        lblWarn.setText("* 비밀번호: 8~16자의 영문 소문자, 숫자를 사용해 주세요. ");

        lblWarn1.setForeground(new java.awt.Color(255, 0, 0));
        lblWarn1.setText("* 비밀번호 확인: 비밀번호가 일치하지 않습니다.");

        Input_PW_text.setBackground(new java.awt.Color(35, 35, 35));
        Input_PW_text.setForeground(new java.awt.Color(255, 255, 255));
        Input_PW_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_PW_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Input_PWC_text.setBackground(new java.awt.Color(35, 35, 35));
        Input_PWC_text.setForeground(new java.awt.Color(255, 255, 255));
        Input_PWC_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_PWC_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblBack4.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        lblBack4.setForeground(new java.awt.Color(255, 255, 255));
        lblBack4.setText("◀");
        lblBack4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBack4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ChangePWLayout = new javax.swing.GroupLayout(ChangePW);
        ChangePW.setLayout(ChangePWLayout);
        ChangePWLayout.setHorizontalGroup(
            ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePWLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPW)
                    .addComponent(lblPWC))
                .addGap(55, 55, 55)
                .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Input_PWC_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Input_PW_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ChangePWLayout.createSequentialGroup()
                .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePWLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnCancel)
                        .addGap(68, 68, 68)
                        .addComponent(btnChangePW))
                    .addGroup(ChangePWLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack4)
                        .addGap(90, 90, 90)
                        .addComponent(lblChangePW))
                    .addGroup(ChangePWLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarn1)
                            .addComponent(lblWarn))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        ChangePWLayout.setVerticalGroup(
            ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePWLayout.createSequentialGroup()
                .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChangePWLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblChangePW))
                    .addGroup(ChangePWLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input_PW_text, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPW))
                .addGap(27, 27, 27)
                .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPWC)
                    .addComponent(Input_PWC_text, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lblWarn)
                .addGap(18, 18, 18)
                .addComponent(lblWarn1)
                .addGap(42, 42, 42)
                .addGroup(ChangePWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePW)
                    .addComponent(btnCancel))
                .addGap(59, 59, 59))
        );

        getContentPane().add(ChangePW, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckRequestActionPerformed
        try {
            boolean lengthBool = false;

            if (txtBirth.getText().length() == 8) {
                lengthBool = true;
            }

            if (txtName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "이름을 입력하세요.");
            } else if (txtBirth.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "생년월일을 입력하세요.");
            } else if (lengthBool == false) {
                JOptionPane.showMessageDialog(null, "올바른 생년월일 8자리를 입력하세요.");
            } else if (txtPN1.getText().trim().equals("") || txtPN2.getText().trim().equals("") || txtPN3.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "전화번호를 입력하세요.");
            } else {
                phoneNum = txtPN1.getText().trim() + "-";
                phoneNum += txtPN2.getText().trim() + "-";
                phoneNum += txtPN3.getText().trim();
                btnCheckRequest.setEnabled(false);
                lblCheck.setVisible(true);
                txtCheck.setVisible(true);
                btnCheck.setVisible(true);
            }
        } catch (Exception ex) {
            System.out.println("Check_Request Error");
        }
    }//GEN-LAST:event_btnCheckRequestActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        boolean IDPhoneCheck = false;
        String User_ID = null;
        String User_Name;
        String User_Birth;
        String User_Phone;

        try {
            if (txtCheck.getText().trim().equals("0000")) {
                try {
                    String sql = "select * from users"; //sql명령문
                    Connection con = DriverManager.getConnection(orcle_url, orcle_ID, orcle_PW); // DB 연결
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery(sql);
                    // DB 접근과정

                    // 1. 이름 생년월일 전화번호 일치 확인
                    while (rs.next()) {
                        User_ID = rs.getString("User_ID");
                        User_Name = rs.getString("User_Name");
                        User_Birth = rs.getString("User_Birth");
                        User_Phone = rs.getString("User_Phone");
                        if (User_Phone.equals(phoneNum) && User_Name.equals(txtName.getText().trim()) && User_Birth.equals(txtBirth.getText().trim())) {
                            System.out.println("Yes");
                            IDPhoneCheck = true;
                            break;
                        }
                    }
                } catch (SQLException ex) {
                    System.out.println("Phone Duplicate Error");
                }
            } else {
                JOptionPane.showMessageDialog(null, "인증번호가 일치하지 않습니다.");
            }

            if (IDPhoneCheck == true && txtCheck.getText().trim().equals("0000")) {
                JOptionPane.showMessageDialog(null, "아이디는 '" + User_ID + "'입니다.");
                dispose();
            } else if (IDPhoneCheck == false && txtCheck.getText().trim().equals("0000")) {
                btnCheckRequest.setEnabled(true);
                lblCheck.setVisible(false);
                txtCheck.setVisible(false);
                btnCheck.setVisible(false);
                txtCheck.setText("");
                JOptionPane.showMessageDialog(null, "가입되지 않은 회원 정보입니다.");
            }
        } catch (Exception ex) {
            System.out.println("PhoneNum Check Error");
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void lblBack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack2MouseClicked
        FindID.setVisible(false);
        Choose.setVisible(true);
    }//GEN-LAST:event_lblBack2MouseClicked

    private void btnCheckRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckRequest1ActionPerformed
        try {
            boolean lengthBool = false;

            if (txtBirth1.getText().length() == 8) {
                lengthBool = true;
            }

            if (txtName1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "이름을 입력하세요.");
            } else if (txtBirth1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "생년월일을 입력하세요.");
            } else if (lengthBool == false) {
                JOptionPane.showMessageDialog(null, "올바른 생년월일 8자리를 입력하세요.");
            } else if (txtPN4.getText().trim().equals("") || txtPN5.getText().trim().equals("") || txtPN6.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "전화번호를 입력하세요.");
            } else {
                phoneNum = txtPN4.getText().trim() + "-";
                phoneNum += txtPN5.getText().trim() + "-";
                phoneNum += txtPN6.getText().trim();
                btnCheckRequest1.setEnabled(false);
                lblCheck1.setVisible(true);
                txtCheck1.setVisible(true);
                btnCheck1.setVisible(true);
            }
        } catch (Exception ex) {
            System.out.println("Check_Request Error");
        }
    }//GEN-LAST:event_btnCheckRequest1ActionPerformed

    private void btnCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheck1ActionPerformed
        boolean PWPhoneCheck = false;
        String User_Name;
        String User_Birth;
        String User_Phone;

        try {
            if (txtCheck1.getText().trim().equals("0000")) {
                try {
                    String sql = "select * from users where User_ID = '" + userID + "'"; //sql명령문
                    Connection con = DriverManager.getConnection(orcle_url, orcle_ID, orcle_PW); // DB 연결
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery(sql);
                    // DB 접근과정

                    // 1. 이름 생년월일 전화번호 일치 확인
                    while (rs.next()) {
                        User_Name = rs.getString("User_Name");
                        User_Birth = rs.getString("User_Birth");
                        User_Phone = rs.getString("User_Phone");
                        if (User_Phone.equals(phoneNum) && User_Name.equals(txtName1.getText().trim()) && User_Birth.equals(txtBirth1.getText().trim())) {
                            System.out.println("Yes");
                            PWPhoneCheck = true;
                            break;
                        }
                    }
                } catch (SQLException ex) {
                    System.out.println("Phone Duplicate Error");
                }
            } else {
                JOptionPane.showMessageDialog(null, "인증번호가 일치하지 않습니다.");
            }

            if (PWPhoneCheck == true && txtCheck1.getText().trim().equals("0000")) {
                FindPW.setVisible(false);
                ChangePW.setVisible(true);
            } else if (PWPhoneCheck == false && txtCheck1.getText().trim().equals("0000")) {
                btnCheckRequest1.setEnabled(true);
                lblCheck1.setVisible(false);
                txtCheck1.setVisible(false);
                btnCheck1.setVisible(false);
                txtCheck1.setText("");
                JOptionPane.showMessageDialog(null, "회원정보가 일치하지 않습니다.");
            }
        } catch (Exception ex) {
            System.out.println("PhoneNum Check Error");
        }
    }//GEN-LAST:event_btnCheck1ActionPerformed

    private void lblBack3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack3MouseClicked
        InputID.setVisible(true);
        FindPW.setVisible(false);
    }//GEN-LAST:event_lblBack3MouseClicked

    private void btnFindPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindPWActionPerformed
        Choose.setVisible(false);
        InputID.setVisible(true);
    }//GEN-LAST:event_btnFindPWActionPerformed

    private void btnFindIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindIDActionPerformed
        Choose.setVisible(false);
        FindID.setVisible(true);
    }//GEN-LAST:event_btnFindIDActionPerformed

    private void btnInputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputIDActionPerformed
        boolean IDCheck = false;
        try {
            String sql = "select USER_ID from users"; //sql명령문
            Connection con = DriverManager.getConnection(orcle_url, orcle_ID, orcle_PW); // DB 연결
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            // DB 접근과정

            while (rs.next()) {
                userID = rs.getString("USER_ID");
                if (userID.equals(txtInputID.getText().trim())) {
                    IDCheck = true;
                    InputID.setVisible(false);
                    FindPW.setVisible(true);
                    break;
                }
            }
        } catch (SQLException ex) {
            System.out.println("Phone Duplicate Error");
        }
        if(IDCheck == false){
            JOptionPane.showMessageDialog(null, "가입되지 않은 아이디입니다.");
        }
    }//GEN-LAST:event_btnInputIDActionPerformed

    private void btnChangePWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePWActionPerformed
        try {
            String sql = "Update USERS Set USER_PW = ? where User_ID = '" + userID + "'"; // DML 명령어
            Connection con = DriverManager.getConnection(Main.orcle_url, Main.orcle_ID, Main.orcle_PW); // DB 연결
            PreparedStatement pstmt = con.prepareStatement(sql);

            boolean lengthBool = false;
            boolean numBool = false;
            boolean engBool = false;

            if (Input_PW_text.getText().length() >= 8 && Input_PW_text.getText().length() <= 16) {
                lengthBool = true;
            }
            // 비밀번호 문자로 쪼개서 검사
            if (Input_PW_text.getText().length() > 0) {
                String[] token = Input_PW_text.getText().split("");
                for (int i = 0; i < token.length; i++) {
                    char c = token[i].charAt(0);
                    if (c > 48 && c < 57) {
                        numBool = true;
                    }
                    if (c > 97 && c < 122) {
                        engBool = true;
                    }
                }
            }

            if (lengthBool == true && numBool == true && engBool == true) {
                lblWarn.setForeground(ChangePW.getBackground());
            }
            if (Input_PW_text.getText().equals(Input_PWC_text.getText())) {
                lblWarn1.setForeground(ChangePW.getBackground());
            }

            // DB 접근과정
            if (Input_PW_text.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "비밀번호를 입력하세요.");
            } else if (lengthBool == false || numBool == false || engBool == false) {
                lblWarn.setForeground(Color.red);
            } else if (!(Input_PW_text.getText().equals(Input_PWC_text.getText()))) {
                lblWarn1.setForeground(Color.red);
            } else {
                pstmt.setString(1, Input_PW_text.getText());
                pstmt.executeUpdate(); //입력값 DB 업데이트
                JOptionPane.showMessageDialog(null, "비밀번호 변경 완료");
                dispose();
            }
        } catch (SQLException ex) {
            System.out.println("ChangePW Error" + ex.getMessage());
        }
    }//GEN-LAST:event_btnChangePWActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //창 닫기
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        InputID.setVisible(false);
        Choose.setVisible(true);
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBack4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBack4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangePW;
    private javax.swing.JPanel Check;
    private javax.swing.JPanel Check1;
    private javax.swing.JPanel Choose;
    private javax.swing.JPanel FindID;
    private javax.swing.JPanel FindPW;
    private javax.swing.JPanel InputID;
    private javax.swing.JPasswordField Input_PWC_text;
    private javax.swing.JPasswordField Input_PW_text;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangePW;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnCheck1;
    private javax.swing.JButton btnCheckRequest;
    private javax.swing.JButton btnCheckRequest1;
    private javax.swing.JButton btnFindID;
    private javax.swing.JButton btnFindPW;
    private javax.swing.JButton btnInputID;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBack2;
    private javax.swing.JLabel lblBack3;
    private javax.swing.JLabel lblBack4;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblBirth1;
    private javax.swing.JLabel lblChangePW;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblCheck1;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblCom2;
    private javax.swing.JLabel lblCom5;
    private javax.swing.JLabel lblFindPW;
    private javax.swing.JLabel lblHypen1;
    private javax.swing.JLabel lblHypen2;
    private javax.swing.JLabel lblHypen3;
    private javax.swing.JLabel lblHypen4;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInputID;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblN1;
    private javax.swing.JLabel lblPN;
    private javax.swing.JLabel lblPN1;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblPWC;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblWarn;
    private javax.swing.JLabel lblWarn1;
    private javax.swing.JRadioButton radioKT;
    private javax.swing.JRadioButton radioKT1;
    private javax.swing.JRadioButton radioLG;
    private javax.swing.JRadioButton radioLG1;
    private javax.swing.JRadioButton radioSKT;
    private javax.swing.JRadioButton radioSKT1;
    private javax.swing.JTextField txtBirth;
    private javax.swing.JTextField txtBirth1;
    private javax.swing.JTextField txtCheck;
    private javax.swing.JTextField txtCheck1;
    private javax.swing.JTextField txtInputID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPN1;
    private javax.swing.JTextField txtPN2;
    private javax.swing.JTextField txtPN3;
    private javax.swing.JTextField txtPN4;
    private javax.swing.JTextField txtPN5;
    private javax.swing.JTextField txtPN6;
    // End of variables declaration//GEN-END:variables
}
