package sw;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import static sw.Main.orcle_ID;
import static sw.Main.orcle_PW;
import static sw.Main.orcle_url;

public class Sign_Up extends javax.swing.JFrame {
   
    boolean status = false; //중복검사 확인 (중복 검사버튼을 누르지 않으면 회원가입 불가)
    
    public Sign_Up() {
        initComponents();
        lblWarn.setForeground(Sign.getBackground());
        lblWarn1.setForeground(Sign.getBackground());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sign = new javax.swing.JPanel();
        Sign_Up_Label = new javax.swing.JLabel();
        Input_ID_text = new javax.swing.JTextField();
        Sign_button = new javax.swing.JButton();
        Cancel_button = new javax.swing.JButton();
        Input_Name_text = new javax.swing.JTextField();
        Input_PW_text = new javax.swing.JTextField();
        Input_PWC_text = new javax.swing.JTextField();
        Duplicate_button = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        lblPWC = new javax.swing.JLabel();
        lblWarn = new javax.swing.JLabel();
        lblWarn1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sign.setBackground(new java.awt.Color(35, 35, 35));
        Sign.setMaximumSize(new java.awt.Dimension(405, 410));
        Sign.setMinimumSize(new java.awt.Dimension(405, 410));
        Sign.setPreferredSize(new java.awt.Dimension(405, 410));

        Sign_Up_Label.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        Sign_Up_Label.setForeground(new java.awt.Color(255, 255, 255));
        Sign_Up_Label.setText("회원 가입");

        Input_ID_text.setBackground(new java.awt.Color(25, 25, 25));
        Input_ID_text.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Input_ID_text.setForeground(new java.awt.Color(255, 255, 255));
        Input_ID_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_ID_text.setActionCommand("<Not Set>");
        Input_ID_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Input_ID_text.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Sign_button.setBackground(new java.awt.Color(211, 211, 211));
        Sign_button.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Sign_button.setText("회원 가입");
        Sign_button.setEnabled(false);
        Sign_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_buttonActionPerformed(evt);
            }
        });

        Cancel_button.setBackground(new java.awt.Color(211, 211, 211));
        Cancel_button.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Cancel_button.setText("취소");
        Cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_buttonActionPerformed(evt);
            }
        });

        Input_Name_text.setBackground(new java.awt.Color(25, 25, 25));
        Input_Name_text.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Input_Name_text.setForeground(new java.awt.Color(255, 255, 255));
        Input_Name_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_Name_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Input_PW_text.setBackground(new java.awt.Color(25, 25, 25));
        Input_PW_text.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Input_PW_text.setForeground(new java.awt.Color(255, 255, 255));
        Input_PW_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_PW_text.setToolTipText("");
        Input_PW_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Input_PWC_text.setBackground(new java.awt.Color(25, 25, 25));
        Input_PWC_text.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Input_PWC_text.setForeground(new java.awt.Color(255, 255, 255));
        Input_PWC_text.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_PWC_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Duplicate_button.setBackground(new java.awt.Color(211, 211, 211));
        Duplicate_button.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Duplicate_button.setText("중복 확인");
        Duplicate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Duplicate_buttonActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");

        lblName.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("이름");

        lblPW.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPW.setForeground(new java.awt.Color(255, 255, 255));
        lblPW.setText("비밀번호");

        lblPWC.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPWC.setForeground(new java.awt.Color(255, 255, 255));
        lblPWC.setText("비밀번호 확인");

        lblWarn.setForeground(new java.awt.Color(255, 0, 0));
        lblWarn.setText("* 비밀번호: 8~16자의 영문 소문자, 숫자를 사용해 주세요. ");

        lblWarn1.setForeground(new java.awt.Color(255, 0, 0));
        lblWarn1.setText("* 비밀번호 확인: 비밀번호가 일치하지 않습니다.");

        javax.swing.GroupLayout SignLayout = new javax.swing.GroupLayout(Sign);
        Sign.setLayout(SignLayout);
        SignLayout.setHorizontalGroup(
            SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cancel_button)
                .addGap(67, 67, 67)
                .addComponent(Sign_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(SignLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignLayout.createSequentialGroup()
                        .addComponent(Sign_Up_Label)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblWarn)
                        .addGroup(SignLayout.createSequentialGroup()
                            .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPWC)
                                .addComponent(lblPW, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblID, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(15, 15, 15)
                            .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Input_PWC_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Input_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SignLayout.createSequentialGroup()
                                    .addComponent(Input_ID_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Duplicate_button))
                                .addComponent(Input_PW_text, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblWarn1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        SignLayout.setVerticalGroup(
            SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Sign_Up_Label)
                .addGap(48, 48, 48)
                .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input_ID_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Duplicate_button)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input_PW_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPW))
                .addGap(18, 18, 18)
                .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Input_PWC_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPWC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWarn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWarn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(SignLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sign_button)
                    .addComponent(Cancel_button))
                .addGap(59, 59, 59))
        );

        getContentPane().add(Sign, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void Sign_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_Sign_buttonActionPerformed
        try {
            String sql = "insert into USERS(USER_ID, USER_PW, USER_NAME)" + "values (?,?,?)"; // DML 명령어
            Connection con = DriverManager.getConnection(Main.orcle_url, Main.orcle_ID, Main.orcle_PW); // DB 연결
            PreparedStatement pstmt = con.prepareStatement(sql);
            
            boolean lengthBool = false;
            boolean numBool = false;
            boolean engBool = false;
            
            if (Input_PW_text.getText().length() >= 8 && Input_PW_text.getText().length() <= 16)
                lengthBool = true;
            // 비밀번호 문자로 쪼개서 검사
            if (Input_PW_text.getText().length() > 0){
                String[] token = Input_PW_text.getText().split("");
                for (int i=0; i<token.length; i++){
                    char c = token[i].charAt(0);
                    if(c > 48 && c < 57)
                        numBool = true;
                    if (c > 97 && c < 122)
                        engBool = true;
                }
            }

            if(lengthBool == true && numBool == true && engBool == true){
                lblWarn.setForeground(Sign.getBackground());
            }
            if(Input_PW_text.getText().equals(Input_PWC_text.getText())){
                lblWarn1.setForeground(Sign.getBackground());
            }
            
            // DB 접근과정
            if(Input_Name_text.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "이름을 입력하세요.");
            }
            else if (Input_PW_text.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "비밀번호를 입력하세요.");
            }
            else if(lengthBool == false || numBool == false || engBool == false){
                lblWarn.setForeground(Color.red);
            }
            else if(!(Input_PW_text.getText().equals(Input_PWC_text.getText()))){
                lblWarn1.setForeground(Color.red);
            }
            else{
                pstmt.setString(1, Input_ID_text.getText());
                pstmt.setString(2, Input_PW_text.getText());
                pstmt.setString(3, Input_Name_text.getText());
                pstmt.executeUpdate(); //입력값 DB 업데이트
                JOptionPane.showMessageDialog(null, "회원가입 완료");
                dispose();
            }
        } catch (SQLException ex) {
            System.out.println("Sing_Up Error");
        }
    }//GEN-LAST:event_Sign_buttonActionPerformed

    private void Cancel_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_Cancel_buttonActionPerformed
        //창 닫기
        dispose();
    }//GEN-LAST:event_Cancel_buttonActionPerformed

    private void Duplicate_buttonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_Duplicate_buttonActionPerformed
        try
            {
            String sql = "select USER_ID from users"; //sql명령문
            Connection con = DriverManager.getConnection(orcle_url, orcle_ID, orcle_PW); // DB 연결
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            // DB 접근과정
            
            while(rs.next()){ 
                String User_ID = rs.getString("User_ID");
                if(Input_ID_text.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(null, "아이디를 입력하세요.");
                    status = false;
                    break;
                }
                else if (User_ID.equals(Input_ID_text.getText())){
                    JOptionPane.showMessageDialog(null, "중복된 아이디 입니다.");
                    status = false;
                    break;
                }
                else{
                    System.out.println("Yes");
                    status = true;
                }
            }
            Sign_button.setEnabled(status);
            
        } catch (SQLException ex) {
            System.out.println("Duplicate Error");
        }
            
    }//GEN-LAST:event_Duplicate_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_Up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_Up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_button;
    private javax.swing.JButton Duplicate_button;
    private javax.swing.JTextField Input_ID_text;
    private javax.swing.JTextField Input_Name_text;
    private javax.swing.JTextField Input_PWC_text;
    private javax.swing.JTextField Input_PW_text;
    private javax.swing.JPanel Sign;
    private javax.swing.JLabel Sign_Up_Label;
    private javax.swing.JButton Sign_button;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblPWC;
    private javax.swing.JLabel lblWarn;
    private javax.swing.JLabel lblWarn1;
    // End of variables declaration//GEN-END:variables
}
