import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 산
 */
public class Main extends javax.swing.JFrame {
    
    String orcle_url = "jdbc:oracle:thin:@localhost:1521:orcl"; //DB URL
    String orcle_ID = "c##san"; //DB ID
    String orcle_PW = "123"; // DB Password    
    /**
     * Creates new form Login
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Setting = new javax.swing.JFrame();
        Sing = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Join_ID = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Join_Name = new javax.swing.JTextField();
        Join_PW = new javax.swing.JTextField();
        Join_CPW = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Main = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        Input_PW = new javax.swing.JPasswordField();
        Input_ID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Sing_Up = new javax.swing.JLabel();
        Find_PW = new javax.swing.JLabel();
        Order = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        Setting.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Setting.setPreferredSize(new java.awt.Dimension(356, 402));
        Setting.setSize(new java.awt.Dimension(356, 402));
        Setting.getContentPane().setLayout(new java.awt.CardLayout());

        Sing.setBackground(new java.awt.Color(35, 35, 35));
        Sing.setMinimumSize(new java.awt.Dimension(356, 402));

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("회원가입");

        Join_ID.setBackground(new java.awt.Color(25, 25, 25));
        Join_ID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Join_ID.setForeground(new java.awt.Color(255, 255, 255));
        Join_ID.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Join_ID.setText("ID");
        Join_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton3.setBackground(new java.awt.Color(211, 211, 211));
        jButton3.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        jButton3.setText("계정 생성");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Cancel.setBackground(new java.awt.Color(211, 211, 211));
        Cancel.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Cancel.setText("취소");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Join_Name.setBackground(new java.awt.Color(25, 25, 25));
        Join_Name.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Join_Name.setForeground(new java.awt.Color(255, 255, 255));
        Join_Name.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Join_Name.setText("이름");
        Join_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Join_PW.setBackground(new java.awt.Color(25, 25, 25));
        Join_PW.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Join_PW.setForeground(new java.awt.Color(255, 255, 255));
        Join_PW.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Join_PW.setText("비밀번호");
        Join_PW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Join_CPW.setBackground(new java.awt.Color(25, 25, 25));
        Join_CPW.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Join_CPW.setForeground(new java.awt.Color(255, 255, 255));
        Join_CPW.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Join_CPW.setText("비밀번호 확인");
        Join_CPW.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton5.setBackground(new java.awt.Color(211, 211, 211));
        jButton5.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        jButton5.setText("중복 확인");

        javax.swing.GroupLayout SingLayout = new javax.swing.GroupLayout(Sing);
        Sing.setLayout(SingLayout);
        SingLayout.setHorizontalGroup(
            SingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SingLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(SingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Join_CPW, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Join_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Join_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SingLayout.createSequentialGroup()
                            .addComponent(Cancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SingLayout.createSequentialGroup()
                            .addGroup(SingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Join_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SingLayout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel2)))
                            .addGap(18, 18, 18)
                            .addComponent(jButton5))))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        SingLayout.setVerticalGroup(
            SingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SingLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(SingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Join_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(Join_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Join_PW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Join_CPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(SingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(jButton3))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        Setting.getContentPane().add(Sing, "card2");

        Main.setBackground(new java.awt.Color(35, 35, 35));
        Main.setPreferredSize(new java.awt.Dimension(700, 500));
        Main.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(35, 35, 35));
        Login.setPreferredSize(new java.awt.Dimension(700, 500));

        Input_PW.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_PW.setText("jPasswordField1");
        Input_PW.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_PWFocusGained(evt);
            }
        });
        Input_PW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_PWActionPerformed(evt);
            }
        });

        Input_ID.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        Input_ID.setText("ID");
        Input_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_IDFocusGained(evt);
            }
        });

        jButton1.setText("로그인");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Sing_Up.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Sing_Up.setForeground(new java.awt.Color(255, 255, 255));
        Sing_Up.setText("계정 생성");
        Sing_Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sing_UpMouseClicked(evt);
            }
        });

        Find_PW.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        Find_PW.setForeground(new java.awt.Color(255, 255, 255));
        Find_PW.setText("비밀번호 찾기");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(Sing_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Find_PW))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Input_ID)
                            .addComponent(Input_PW, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(265, 265, 265))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(Input_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Input_PW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sing_Up)
                    .addComponent(Find_PW))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        Main.add(Login, "card3");

        Order.setBackground(new java.awt.Color(35, 35, 35));
        Order.setPreferredSize(new java.awt.Dimension(700, 500));
        Order.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("주문화면");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout OrderLayout = new javax.swing.GroupLayout(Order);
        Order.setLayout(OrderLayout);
        OrderLayout.setHorizontalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGroup(OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel1))
                    .addGroup(OrderLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        OrderLayout.setVerticalGroup(
            OrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        Main.add(Order, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sing_UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sing_UpMouseClicked

        Setting.setVisible(true);

    }//GEN-LAST:event_Sing_UpMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String sql = "select * from users"; //sql명령문
            Connection con = DriverManager.getConnection(orcle_url, orcle_ID, orcle_PW); // DB 연결
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            // DB 접근과정
            
            while(rs.next()){ // 
                String User_ID = rs.getString("User_ID");
                String User_PW = rs.getString("User_PW");
                String User_Name = rs.getString("User_Name");
                if (User_ID.equals(Input_ID.getText()) && User_PW.equals(Input_PW.getText())){ // ID랑 PW같다면 로그인
                    Login.setVisible(false);
                    Order.setVisible(true);
                }
            }
        } catch (SQLException ex) {
            System.err.println("로그인 오류");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Input_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_IDFocusGained
        Input_ID.setText(null);
    }//GEN-LAST:event_Input_IDFocusGained

    private void Input_PWFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_PWFocusGained
        Input_PW.setText(null);
    }//GEN-LAST:event_Input_PWFocusGained

    private void Input_PWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_PWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_PWActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            PreparedStatement pstmt = null;
            String sql = "insert into USERS(USER_ID, USER_PW, USER_NAME)" + "values (?,?,?)"; // DML 명령어
            Connection con = DriverManager.getConnection(orcle_url, orcle_ID, orcle_PW); // DB 연결
            pstmt = con.prepareStatement(sql);
            // DB 접근과정
            pstmt.setString(1, Join_ID.getText());
            pstmt.setString(2, Join_PW.getText());
            pstmt.setString(3, Join_Name.getText());
            pstmt.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "회원가입 완료");
            
            
        } catch (SQLException ex) {
            System.err.println("회원가입 오류");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        Setting.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Find_PW;
    private javax.swing.JTextField Input_ID;
    private javax.swing.JPasswordField Input_PW;
    private javax.swing.JTextField Join_CPW;
    private javax.swing.JTextField Join_ID;
    private javax.swing.JTextField Join_Name;
    private javax.swing.JTextField Join_PW;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Order;
    private javax.swing.JFrame Setting;
    private javax.swing.JPanel Sing;
    private javax.swing.JLabel Sing_Up;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
